### ISSUE TITLE
unhandled exception

### ISSUE THREAD

**Issue by KJS1212** [anderbggo/GooglePhotosMatcher#13]
This error stopped the process from completing

Traceback (most recent call last):
  File "window.py", line 24, in <module>
  File "main.py", line 37, in mainProcess
KeyError: 'title'

It managed to match 2473 media but left 1452 items in the original folder. I have tried to run it again several times but it seems to be stuck on a particular file because every time I run it in this folder now I get the error immediately. Please help!

**Comment by jdmontes2009** [comment]
I'm having the same issue, did you find a fix?

**Comment by tigerorc** [comment]
I'm having the same issue!! I just click MATCH, then the program crash.
I am a chinese user, maybe the file name can not involve space or some specical words...

**Comment by anderbggo** [comment]
> I'm having the same issue!! I just click MATCH, then the program crash.
> I am a chinese user, maybe the file name can not involve space or some specical words...

Hi, the development of this project is currently on hold. My priorities are elsewhere at the moment. 😅 That said, feel free to submit a pull request, and I'll review it within 48h.

Thanks for using my project!

**Comment by turnbom** [comment]
The Error is caused by when the MetaData file in the album folder has nothing in it.
For me seems to be common with folders called Untitled(1) or whatever number.
To fix it I renamed the root folder from Untitled(1) to Broken, then modified the metadata folder to look as follows:

{
  "title": "Broken"
}

after saving it worked fine.

**Comment by anderbggo** [comment]
Fixed in new [release](https://github.com/anderbggo/GooglePhotosMatcher/releases/tag/v2.0)
