### ISSUE TITLE
PermissionError Unhandled Exception in script

### ISSUE THREAD

**Issue by djo5296** [anderbggo/GooglePhotosMatcher#14]
censored the error script, but see below

Traceback (most recent call last):
  File "window.py", line 24, in <module>
  File "main.py", line 61, in mainProcess
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: <<file>> -> <<file>>

not sure if it's because it's a .MP.jpg file

**Comment by nils-simons** [comment]
I have the same error, but not just with .MP.jpg files. I've already tried unlocking the files and restarting the computer, but without any luck.

**Comment by AsherSto** [comment]
I have fixed this here:
[Github repo](https://github.com/AsherSto/GooglePhotosMatcher-FixedPermissions)

Needs recompiling into a new executable though.

**Comment by AsherSto** [comment]
> > I have fixed this here: [Github repo](https://github.com/AsherSto/GooglePhotosMatcher-FixedPermissions)
> > 
> > Needs recompiling into a new executable though.
> 
> Using your repo have the same issue
> 
> ```cmd
> Traceback (most recent call last):
>   File "A:\GF\google-takeout-photos-recover\GooglePhotosMatcher-FixedPermissions\files\window.py", line 24, in <module>
>     mainProcess(values["-IN2-"], window, values['-INPUT_TEXT-'])
>   File "A:\GF\google-takeout-photos-recover\GooglePhotosMatcher-FixedPermissions\files\main.py", line 37, in mainProcess
>     titleOriginal = data['title']  # Store metadata into vars
>                     ~~~~^^^^^^^^^
> KeyError: 'title'
> ```

Not the same issue?

**Comment by Milor123** [comment]
> > > I have fixed this here: [Github repo](https://github.com/AsherSto/GooglePhotosMatcher-FixedPermissions)
> > > Needs recompiling into a new executable though.
> > 
> > 
> > Using your repo have the same issue
> > Traceback (most recent call last):
> >   File "A:\GF\google-takeout-photos-recover\GooglePhotosMatcher-FixedPermissions\files\window.py", line 24, in <module>
> >     mainProcess(values["-IN2-"], window, values['-INPUT_TEXT-'])
> >   File "A:\GF\google-takeout-photos-recover\GooglePhotosMatcher-FixedPermissions\files\main.py", line 37, in mainProcess
> >     titleOriginal = data['title']  # Store metadata into vars
> >                     ~~~~^^^^^^^^^
> > KeyError: 'title'
> 
> Not the same issue?

i dont know bro, but dont work, it silent crash

**Comment by AsherSto** [comment]
Idk man try putting in a try except and find out which file is breaking it, might give you a clue on why there's no title in the meta data for that file

**Comment by nils-simons** [comment]
Hi Everyone,

if I recall correctly I fixed the issue in my fork.
[https://github.com/nils-simons/GooglePhotosMatcher](https://github.com/nils-simons/GooglePhotosMatcher
)

**Comment by mglakner** [comment]
@nils-simons got the error on your fork too.

![Image](https://github.com/user-attachments/assets/9567f6e1-e1f9-4270-bf3c-799069bca633)

**Comment by anderbggo** [comment]
Fixed in new [release](https://github.com/anderbggo/GooglePhotosMatcher/releases/tag/v2.0)
