### ISSUE TITLE
Failed to execute script 'window' due to unhandled exception: 'title'

### ISSUE THREAD

**Issue by Diak** [anderbggo/GooglePhotosMatcher#9]
Hi,

When i click on "Match" button i have this error and the app crashs :

> Traceback (most recent call last):
>   File "window.py", line 24, in <module>
>   File "main.py", line 37, in mainProcess
> KeyError: 'title'

What's wrong ?

I use Windows 11 Pro version 22H2.

**Comment by JoshCodeStuff** [comment]
I am on windows 11 Home. same issue.

**Comment by fishmonkey1** [comment]
same here on Win10

**Comment by ArMaTeC** [comment]
same windows 11

**Comment by rkoehler2017** [comment]
same win11

**Comment by QAQDE** [comment]
Still has the same problem on my windows 11 24H2

**Comment by tigerorc** [comment]
I'm having the same issue!! I just click MATCH, then the program crash.
I am a chinese user, maybe the file name can not involve space or some specical words...

**Comment by mglakner** [comment]
same

**Comment by anderbggo** [comment]
Fixed in new [release](https://github.com/anderbggo/GooglePhotosMatcher/releases/tag/v2.0)
